language: generic
sudo: required
services: 
   - docker

before_install:
  - docker build -t bkuhlen73/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true bkuhlen73/react-test npm test

after_success:
  - docker build -t bkuhlen73/multi-client  ./client
  - docker build -t bkuhlen73/multi-nginx   ./nginx
  - docker build -t bkuhlen73/multi-server  ./server
  - docker build -t bkuhlen73/multi-worker  ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push bkuhlen73/multi-client
  - docker push bkuhlen73/multi-nginx
  - docker push bkuhlen73/multi-server
  - docker push bkuhlen73/multi-worker


deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-1-085415390296"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"